@startuml
skinparam componentStyle uml2

package "Client" {
  [KeyStore]
	[ClientApp] as ClientApp
}

interface "TCP" as TCPAuthServiceAPI
interface "TCP" as TCPFileDeletorAPI
interface "TCP" as TCPFileFetcherAPI
interface "TCP" as TCPFileCreatorAPI

package "Server" as Server {
	[AuthService] as AuthService
	[FileDeletor] as FileDeletor
	[FileFetcher] as FileFetcher
	[FileCreator] as FileCreator
	database "HDFS" as HDFS
	interface "Java API" as HDFSJavaAPI
	database "AuthDB" as AuthDB
	interface "Java API" as AuthDBJavaAPI
}

ClientApp -down-> TCPAuthServiceAPI
ClientApp -down-> TCPFileFetcherAPI
ClientApp -down-> TCPFileCreatorAPI
ClientApp -down-> TCPFileDeletorAPI

TCPAuthServiceAPI -down- AuthService
TCPFileDeletorAPI -down- FileDeletor
TCPFileFetcherAPI -down- FileFetcher
TCPFileCreatorAPI -down- FileCreator

HDFSJavaAPI -down- HDFS
AuthDBJavaAPI -down- AuthDB

FileFetcher --> HDFSJavaAPI
FileCreator --> HDFSJavaAPI
FileDeletor --> HDFSJavaAPI
AuthService --> AuthDBJavaAPI

ClientApp -[hidden]right- KeyStore
AuthService -[hidden]right- FileDeletor
FileDeletor -[hidden]right- FileFetcher
FileFetcher -[hidden]right- FileCreator
Client -[hidden]down- Server
FileFetcher -[hidden]down- HDFSJavaAPI

@enduml
