@startuml

User -[hidden]-> User ++ #yellow
User -> ClientApp ++ #green: имя файла
ClientApp -[hidden]-> ClientAppFileSystem
ClientApp ->o FileFetcher ++ #red: установка соединения

alt FileFetcher доступен
  ClientApp -> FileFetcher: имя файла, логин пользователя, токен, команда, версия сервиса
  FileFetcher -> FileFetcher: проверка токена
    alt токен валиден
      FileFetcher -> FileFetcher: валидация команды
      alt команда валидна
          FileFetcher -> HDFS ++ #white: идентификатор файла, команда
          alt HDFS доступен
            loop передача файла
              HDFS -> FileFetcher: потоковая передача данных файла
              FileFetcher -> ClientApp: потоковая передача данных файла
              ClientApp -> ClientAppFileSystem: потоковая запись данных файла в файл
            end loop
            HDFS -> FileFetcher: Признак конца файла
            FileFetcher -> ClientApp: Признак конца файла
            ClientApp --> User: уведомление о получении файла
            ClientApp ->x FileFetcher: разрыв соединения
          else HDFS не доступен
            FileFetcher --> ClientApp: сообщение об ошибке
            ClientApp --> User: сообщение об ошибке
            ClientApp ->x FileFetcher: разрыв соединения
          end
      else команда не валидна
        FileFetcher --> ClientApp: сообщение об ошибке
        ClientApp --> User: сообщение об ошибке
        ClientApp ->x FileFetcher: разрыв соединения
      end
    else токен не валиден или отсутствует
      FileFetcher --> ClientApp -- #white: сообщение об ошибке
      ClientApp --> User: сообщение об ошибке
      ClientApp ->x FileFetcher: разрыв соединения
    end
else FileFetcher не доступен
  ClientApp --> User -- #green: сообщение об ошибке
end
User -[hidden]-> User -- #yellow

@enduml
