@startuml

User -[hidden]-> User ++ #yellow
User -> ClientApp ++ #green: команда, имя файла
ClientApp -> ClientApp: валидация команды

alt команда валидна
  ClientApp ->o FileFetcher ++ #red: установка соединения
  alt FileFetcher доступен
    ClientApp -> FileFetcher: логин пользователя, токен, команда, версия сервиса
    FileFetcher -> FileFetcher: проверка токена
    alt токен валиден
      FileFetcher -> FileFetcher: валидация команды
      alt команда валидна
          FileFetcher -> HDFS ++ #white: директория, команда
          alt HDFS доступен
            HDFS -> HDFS: получение списка файлов
            HDFS -> FileFetcher -- #white: список файлов
            FileFetcher -> ClientApp: список файлов
            ClientApp --> User: список файлов
            ClientApp ->x FileFetcher: разрыв соединения
          else HDFS не доступен
            FileFetcher --> ClientApp: сообщение об ошибке
            ClientApp --> User: сообщение об ошибке
            ClientApp ->x FileFetcher: разрыв соединения
          end
      else команда не валидна
        FileFetcher --> ClientApp: сообщение об ошибке
        ClientApp --> User: сообщение об ошибке
        ClientApp ->x FileFetcher: разрыв соединения
      end
    else токен не валиден или отсутствует
      FileFetcher --> ClientApp: сообщение об ошибке
      ClientApp --> User: сообщение об ошибке
      ClientApp ->x FileFetcher: разрыв соединения
      FileFetcher -[hidden]-> FileFetcher -- #red
    end
  else FileFetcher не доступен
    ClientApp --> User: сообщение об ошибке
  end
else команда не валидна
    ClientApp --> User -- #green: сообщение об ошибке
end
User -[hidden]-> User -- #yellow

@enduml
